apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/c/Users/Abril/repos/cc-2023-2/proyecto/src"
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim
spec:
  storageClassName: hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plant-classifier
  name: plant-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-classifier
  template:
    metadata:
      labels:
        app: plant-classifier
    spec:
      volumes: 
        - name: plant-volume
          # persistentVolumeClaim:
          #   claimName: persistent-volume-claim
          hostPath: 
            path: /mnt/c/Users/Abril/repos/cc-2023-2/proyecto/src
            type: DirectoryOrCreate
      containers:
      - name: plant-classifier
        image: strobebug/plant-classifier:1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /home/jovyan/work
            name: plant-volume
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: plant-classifier
  name: plant-classifier
spec:
  selector:
    app: plant-classifier
  type: NodePort
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30000