apiVersion: v1
kind: Service
metadata:
  name: plant-classifier-service
spec:
  selector:
    app: plant-classifier
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-classifier
spec:
  selector:
    matchLabels:
      app: plant-classifier
  replicas: 5
  template:
    metadata:
      labels:
        app: plant-classifier
    spec:
      containers:
      - name: plant-classifier
        image: strobebug/plant-classifier:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred