apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "C:/Users/Abril/repos/cc-2023-2/proyecto/src"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plant-classifier
  name: plant-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-classifier
  template:
    metadata:
      labels:
        app: plant-classifier
    spec:
      containers:
      - name: plant-classifier
        image: strobebug/plant-classifier:1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /home/jovyan/data
            name: volume
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: volume-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: plant-classifier
  name: plant-classifier
spec:
  selector:
    app: plant-classifier
  type: NodePort
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30000